user1 = User.create(name: "Alex", email: "alex@email.com", password: "123456")
user2 = User.create(name: "Pedro", email: "pedro@email.com", password: "123456")
user3 = User.create(name: "Laura", email: "laura@email.com", password: "123456")
user4 = User.create(name: "Jonny", email: "jonny@email.com", password: "123456")
user5 = User.create(name: "Alfon", email: "alfon@email.com", password: "123456")
